---
title: "Homework 3 Drafting Viz"
author: "Rachel Swick"
date: last-modified 
format:
  html:
    embed-resources: true
toc: true
warning: false
message: false
eval: true
echo: true
code-fold: true
fig-align: "center"
---


## Learning Objectives
HW #3 will have you focus on making more progress towards completing your final assignment (HW #4). As a reminder, your final assignment is meant to combine all of the course learning outcomes(!):

- identify which types of visualizations are most appropriate for your data and your audience
- prepare (e.g. clean, explore, wrangle) data so that its appropriately formatted for building data visualizations
- build effective, responsible, accessible, and aesthetically-pleasing visualizations using the R programming language, and specifically {ggplot2} + ggplot2 extension packages
- write code from scratch and read and adapt code written by others
- apply a DEI (Diversity, Equity & Inclusion) lens to the process of designing data visualizations
- assess, critique, and provide constructive feedback on data visualizations


## Exercises and Questions

1. I plan to pursue Option 1.

2. Main Question: How does rain fall in Santa Barbara County?
  - The main question has stayed the same since homework 1 but the sub-questions have morphed as I play with the data and how I can visualize it. I want to set up my infographic so that each of my graphs within my infographic answers a different question about how rain has changed in Santa Barbara County over time.
    1) During what months and days of the year does it rain the most in Santa Barbara County?
    2) How have periods of drought changed over the course of the last 100 years? Are droughts just as common but they last longer, or are they also more frequent? General plan for how to answer this question:
        Take the sum of rain by year, averaged across gauges. Then take the average total rain per year. Create a new column with amount of rain above or below the historic average.
    3) How does amount of rainfall differ between different elevation ranges? Is this trend the same in the 20th and 21st centuries? General plan for how to answer this question:
        Put rain gauge elevations into 3 bins based on maximum and minimum elevations over all rain gauges. 

    
3.













